# Generated by Django 4.2.6 on 2023-10-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('score_user', models.IntegerField(verbose_name='Очки игрока')),
                ('score_pc', models.IntegerField(verbose_name='Очки Компьютера')),
            ],
        ),
    ]
