# Generated by Django 4.2.6 on 2023-10-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'Результат', 'verbose_name_plural': 'Результаты'},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='score_pc',
            field=models.IntegerField(null=True, verbose_name='Очки Компьютера'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='score_user',
            field=models.IntegerField(null=True, verbose_name='Очки игрока'),
        ),
    ]
